export type SchoolCollection =
  | 'info'
  | 'students'
  | 'teachers'
  | 'parents'
  | 'classes'
  | 'timetables'
  | 'fee_records'
  | 'notifications'
  | 'calendar_events'
  | 'conversations'
  | 'payments'
  | 'payment_transactions'
  | 'fee_invoices'
  | 'sports'
  | 'culture'
  | 'teams'
  | 'events'
  | 'awards'
  | 'achievements'
  | 'student_recognition'
  | 'lunch_menus'
  | 'daily_meals'
  | 'notification_preferences';

export type TenantScopedPath = `schools/${string}/${SchoolCollection}`;
